### PR TITLE
New resource FileSystemAccessRule

### PR DESCRIPTION
**Pull request by johlju**
- FileSystemDsc
  - Added resource FileSystemAccessRule

*This PR moves the resource xFileSystemAccessRule from the module xSystemSecurity to this module. This PR will make it possible to deprecate the module xSystemSecurity.*

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO I trade you reviews. 😉  This is a big one so no hurry.

**Review by gaelcolas — CHANGES_REQUESTED** [review]
Did a quick review and spotted some quick changes.
Maybe worth for Daniel -eagle eye- Scott-Raynsford to double check though, as I went fast ;)

> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-:-M0hWkOy-6YbaZ7k_bWe:bpaydlv)* status: all files reviewed, 4 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[CHANGELOG.md, line 13 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hUEff-OyvKUN_wA68:-M0hUEfgDV7-LiQxreci:b-uyu477) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/CHANGELOG.md#L13)):*
> ```Markdown
>   - Added resource FileSystemAccessRule
> 
> ### Changed
> ```

You probably want to clean up those not in use here?
___
*[RequiredModules.psd1, line 22 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hVWnf0gHcaow1cpHe:-M0hVWnf0gHcaow1cpHf:b-xitw9c) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/RequiredModules.psd1#L22)):*
> ```PowerShell
>     xDscResourceDesigner        = 'latest'
>     'DscResource.DocGenerator'  = 'latest'
>     'DscResource.Common'        = '0.2.0'
> ```

Are you sure you want to pin DscResource.Common?
I'd prefer leaving to latest, and the day a new version of DscResource.Common breaks a build, pin it to previous working version until it's fixed.
___
*[tests/Integration/DSC_FileSystemAccessRule.Integration.Tests.ps1, line 11 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hWLHR5wFXzWQGlnIC:-M0hWLHR5wFXzWQGlnID:btj97g1) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/tests/Integration/DSC_FileSystemAccessRule.Integration.Tests.ps1#L11)):*
> ```PowerShell
> catch [System.IO.FileNotFoundException]
> {
>     throw 'DscResource.Test module dependency not found. Please run ".\build.ps1 -Tasks build" first.'
> ```

should this be `-ResolveDependency` as well, or you just rely on the autoResolve?
___
*[tests/Unit/DSC_FileSystemAccessRule.Tests.ps1, line 12 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hWbk70dqWLCV_lgLq:-M0hWbk70dqWLCV_lgLr:bb7od0r) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/tests/Unit/DSC_FileSystemAccessRule.Tests.ps1#L12)):*
> ```PowerShell
>     catch [System.IO.FileNotFoundException]
>     {
>         throw 'DscResource.Test module dependency not found. Please run ".\build.ps1 -Tasks build" first.'
> ```

same

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1)* status: 27 of 29 files reviewed, 4 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[CHANGELOG.md, line 13 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hUEff-OyvKUN_wA68:-M0hiBnN0SrWOsEDWnf2:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/CHANGELOG.md#L13)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

You probably want to clean up those not in use here?
</blockquote></details>

Done.
___
*[RequiredModules.psd1, line 22 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hVWnf0gHcaow1cpHe:-M0hiDAC3Ww45mE6JeEG:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/RequiredModules.psd1#L22)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

Are you sure you want to pin DscResource.Common?
I'd prefer leaving to latest, and the day a new version of DscResource.Common breaks a build, pin it to previous working version until it's fixed.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_FileSystemAccessRule.Integration.Tests.ps1, line 11 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hWLHR5wFXzWQGlnIC:-M0hiEg3CSg9D1m4QH6i:b-ibves7) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/tests/Integration/DSC_FileSystemAccessRule.Integration.Tests.ps1#L11)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

should this be `-ResolveDependency` as well, or you just rely on the autoResolve?
</blockquote></details>

I think something else (help doc) should mention the prereq for running `build`? :thinking: 
___
*[tests/Unit/DSC_FileSystemAccessRule.Tests.ps1, line 12 at r1](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M0hWbk70dqWLCV_lgLq:-M0hiRFNAQEgsk7L-rDT:b-ibves7) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/6991eff4a8a5225d94d26b9ad24a83fba512690d/tests/Unit/DSC_FileSystemAccessRule.Tests.ps1#L12)):*
<details><summary><i>Previously, gaelcolas (Gael) wrote…</i></summary><blockquote>

same
</blockquote></details>

I think something else (help doc) should mention the prereq for running `build`? :thinking:

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 5 of 29 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1)* status: all files reviewed, 8 unresolved discussions (waiting on @gaelcolas and @johlju)

___
*[azure-pipelines.yml, line 49 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lss3S5ZKTzuwDHAtP:-M1lss3S5ZKTzuwDHAtQ:b-yx3b5l) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/azure-pipelines.yml#L49)):*
> ```YAML
>               publishLocation: 'Container'
> 
>   - stage: Test
> ```

Can you also run unit/integration tests in WS2016 as well?
___
*[azure-pipelines.yml, line 117 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lsmmq2pAEuKNgOfXe:-M1lsmmq2pAEuKNgOfXf:b-1d13pe) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/azure-pipelines.yml#L117)):*
> ```YAML
>         displayName: 'Integration'
>         pool:
>           vmImage: 'win1803'
> ```

Can you use windows-2019 instead?
___
*[tests/Integration/DSC_FileSystemAccessRule.config.ps1, line 2 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lqoro7yx0OqwQQk7T:-M1lqoro7yx0OqwQQk7U:b56aebo) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/tests/Integration/DSC_FileSystemAccessRule.config.ps1#L2)):*
> ```PowerShell
> $configFile = [System.IO.Path]::ChangeExtension($MyInvocation.MyCommand.Path, 'json')
> if (Test-Path -Path $configFile)
> ```

Add blank line before?
___
*[tests/Integration/DSC_FileSystemAccessRule.config.ps1, line 181 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lrJsr7xBiQ2ci9FlT:-M1lrJsr7xBiQ2ci9FlU:b1pwqim) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/tests/Integration/DSC_FileSystemAccessRule.config.ps1#L181)):*
> ```PowerShell
>     .SYNOPSIS
>         Removes only the specified access rules for the identity when the
>         identity in the current state have more rights than desired state.
> ```

have -> has

**Review by PlagueHO — COMMENTED** [review]
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1)* status: all files reviewed, 9 unresolved discussions (waiting on @gaelcolas and @johlju)

___
*[build.ps1, line 11 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lt0Ax74qlBLw0Z82j:-M1lt0Ax74qlBLw0Z82k:b65546c) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/build.ps1#L11)):*
> ```PowerShell
> (
>     [Parameter(Position = 0)]
>     [string[]]$Tasks = '.',
> ```

Nit pick:
$Tasks on the next line...

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 22 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1)* status: all files reviewed, 15 unresolved discussions (waiting on @gaelcolas and @johlju)

___
*[source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.psm1, line 509 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lxaML8dZxTPEqxamJ:-M1lxaML8dZxTPEqxamK:b-h0rzn6) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.psm1#L509)):*
> ```PowerShell
> 
>                     # If any rights that we want to deny are individually a full subset of existing rights.
>                     $currentRightResult = -not ($rightNotAllowed -eq ($rightNotAllowed -band ([System.Security.AccessControl.FileSystemRights] $currentState.Rights)))
> ```

Is there any way to reduce the length of this line?
___
*[source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof, line 4 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lxAJ08LEKcUuJr9oQ:-M1lxAJ08LEKcUuJr9oR:bjkm7es) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof#L4)):*
> ```
> class DSC_FileSystemAccessRule : OMI_BaseResource
> {
>     [Key, Description("The path to the item that should have permissions set")] string Path;
> ```

Nitpick- end description with full stop.
___
*[source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof, line 5 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lx7Fb4dBwrYoniywk:-M1lx7Fb4dBwrYoniywl:bjkm7es) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof#L5)):*
> ```
> {
>     [Key, Description("The path to the item that should have permissions set")] string Path;
>     [Key, Description("The identity to set permissions for")] string Identity;
> ```

Nitpick- end description with full stop.
___
*[source/DSCResources/DSC_FileSystemAccessRule/en-US/DSC_FileSystemAccessRule.strings.psd1, line 12 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lv57v4DvgFwz8jQtD:-M1lv57v4DvgFwz8jQtE:b-qmgdg8) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/en-US/DSC_FileSystemAccessRule.strings.psd1#L12)):*
> ```PowerShell
>     NotPossibleClusterResourceOwner = The node '{0}' is not a possible owner for the path '{1}'. (FSAR0007)
>     NoClusterDiskPartitionFound = No cluster disk partition was found that the path '{0}' could belong to. (FSAR0008)
>     NodeIsNotClusterMember = 'Node does not belong to a Windows Server Failover Cluster. (FSAR0009)
> ```

There is a ' at the beginning that shouldn't be there.
___
*[source/Examples/README.md, line 4 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lu6g47msb6YOMsrnQ:-M1lu6g47msb6YOMsrnR:bhbtfzk) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/Examples/README.md#L4)):*
> ```Markdown
> 
> This will help to understand how to setup certain scenarios with the
> FIleSystemDsx resource module.
> ```

FIleSystemDsx->FileSystemDsc

Also, capitalization problems.
___
*[tests/Unit/DSC_FileSystemAccessRule.Tests.ps1, line 251 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lwKIeC_tiuBhVCC1G:-M1lwKIeC_tiuBhVCC1H:b-r1udsv) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/tests/Unit/DSC_FileSystemAccessRule.Tests.ps1#L251)):*
> ```PowerShell
> 
>                 Context 'When the configuration is present' {
>                     Context 'When the path exist' {
> ```

exists

**Review by johlju — COMMENTED** [review]
Thank you for these comments! Great catches! :smiley: 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-:-M1oBbNQC9WkRfBOALIo:b-p3m4td)* status: 21 of 29 files reviewed, 14 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[azure-pipelines.yml, line 49 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lss3S5ZKTzuwDHAtP:-M1oBgwqA78-8SiExQSl:b-4x1q25) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/azure-pipelines.yml#L49)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also run unit/integration tests in WS2016 as well?
</blockquote></details>

Done. I tried, hopefully the tests passes. :smile: 
___
*[azure-pipelines.yml, line 117 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lsmmq2pAEuKNgOfXe:-M1oBqCECSm2NB43KNSP:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/azure-pipelines.yml#L117)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you use windows-2019 instead?
</blockquote></details>

Done.
___
*[build.ps1, line 11 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lt0Ax74qlBLw0Z82j:-M1oBs26DA-82e1Q-rnE:b-91iemd) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/build.ps1#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nit pick:
$Tasks on the next line...
</blockquote></details>

Done. Auto-formatted this as well. We need to fix this in sampler. See if I have time to go through that repo an clean it up.
___
*[source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.psm1, line 509 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lxaML8dZxTPEqxamJ:-M1oC4RnE799zpX-UtwB:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.psm1#L509)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is there any way to reduce the length of this line?
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof, line 4 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lxAJ08LEKcUuJr9oQ:-M1oC5-26dZUFxWqNJmZ:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick- end description with full stop.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof, line 5 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lx7Fb4dBwrYoniywk:-M1oC5Gy33Q720-1nJQZ:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/DSC_FileSystemAccessRule.schema.mof#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick- end description with full stop.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_FileSystemAccessRule/en-US/DSC_FileSystemAccessRule.strings.psd1, line 12 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lv57v4DvgFwz8jQtD:-M1oC60U8d155MCA3KJ8:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/DSCResources/DSC_FileSystemAccessRule/en-US/DSC_FileSystemAccessRule.strings.psd1#L12)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

There is a ' at the beginning that shouldn't be there.
</blockquote></details>

Done.
___
*[source/Examples/README.md, line 4 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lu6g47msb6YOMsrnQ:-M1oC6dX7VIrpmX3iBAg:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/source/Examples/README.md#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

FIleSystemDsx->FileSystemDsc

Also, capitalization problems.
</blockquote></details>

Done.
___
*[tests/Integration/DSC_FileSystemAccessRule.config.ps1, line 2 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lqoro7yx0OqwQQk7T:-M1oC7Ce6ebKuAw5chYg:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/tests/Integration/DSC_FileSystemAccessRule.config.ps1#L2)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Add blank line before?
</blockquote></details>

Done.
___
*[tests/Integration/DSC_FileSystemAccessRule.config.ps1, line 181 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lrJsr7xBiQ2ci9FlT:-M1oC7fb3Mu3wF6-r0Pl:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/tests/Integration/DSC_FileSystemAccessRule.config.ps1#L181)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

have -> has
</blockquote></details>

Done.
___
*[tests/Unit/DSC_FileSystemAccessRule.Tests.ps1, line 251 at r2](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-M1lwKIeC_tiuBhVCC1G:-M1oC9A50BdrnG5g-YZL:b-896fix) ([raw file](https://github.com/dsccommunity/filesystemdsc/blob/552c5753f44e06b51fecbd0f92af0fe292ca30bf/tests/Unit/DSC_FileSystemAccessRule.Tests.ps1#L251)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

exists
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1)* status: all files reviewed, 4 unresolved discussions (waiting on @gaelcolas)

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/filesystemdsc/1#-:-M1yEScK7kSIP01bflVf:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @gaelcolas)

**Comment by johlju** [comment]
@PlagueHO cool! Thank you! 😄

**Pull request merged**
